// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pochuman/keysign_vote_data.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type KeysignVoteData struct {
	Index  string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	TxHash string `protobuf:"bytes,2,opt,name=txHash,proto3" json:"txHash,omitempty"`
	PubKey string `protobuf:"bytes,3,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	Voter  string `protobuf:"bytes,4,opt,name=voter,proto3" json:"voter,omitempty"`
	TxTime string `protobuf:"bytes,5,opt,name=txTime,proto3" json:"txTime,omitempty"`
}

func (m *KeysignVoteData) Reset()         { *m = KeysignVoteData{} }
func (m *KeysignVoteData) String() string { return proto.CompactTextString(m) }
func (*KeysignVoteData) ProtoMessage()    {}
func (*KeysignVoteData) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f1fffec15c7a90e, []int{0}
}
func (m *KeysignVoteData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KeysignVoteData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KeysignVoteData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KeysignVoteData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeysignVoteData.Merge(m, src)
}
func (m *KeysignVoteData) XXX_Size() int {
	return m.Size()
}
func (m *KeysignVoteData) XXX_DiscardUnknown() {
	xxx_messageInfo_KeysignVoteData.DiscardUnknown(m)
}

var xxx_messageInfo_KeysignVoteData proto.InternalMessageInfo

func (m *KeysignVoteData) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *KeysignVoteData) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *KeysignVoteData) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *KeysignVoteData) GetVoter() string {
	if m != nil {
		return m.Voter
	}
	return ""
}

func (m *KeysignVoteData) GetTxTime() string {
	if m != nil {
		return m.TxTime
	}
	return ""
}

func init() {
	proto.RegisterType((*KeysignVoteData)(nil), "vigorousdeveloper.pochuman.pochuman.KeysignVoteData")
}

func init() { proto.RegisterFile("pochuman/keysign_vote_data.proto", fileDescriptor_4f1fffec15c7a90e) }

var fileDescriptor_4f1fffec15c7a90e = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x28, 0xc8, 0x4f, 0xce,
	0x28, 0xcd, 0x4d, 0xcc, 0xd3, 0xcf, 0x4e, 0xad, 0x2c, 0xce, 0x4c, 0xcf, 0x8b, 0x2f, 0xcb, 0x2f,
	0x49, 0x8d, 0x4f, 0x49, 0x2c, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x52, 0x2e, 0xcb,
	0x4c, 0xcf, 0x2f, 0xca, 0x2f, 0x2d, 0x4e, 0x49, 0x2d, 0x4b, 0xcd, 0xc9, 0x2f, 0x48, 0x2d, 0xd2,
	0x83, 0xe9, 0x81, 0x33, 0x94, 0x5a, 0x19, 0xb9, 0xf8, 0xbd, 0x21, 0x06, 0x84, 0xe5, 0x97, 0xa4,
	0xba, 0x24, 0x96, 0x24, 0x0a, 0x89, 0x70, 0xb1, 0x66, 0xe6, 0xa5, 0xa4, 0x56, 0x48, 0x30, 0x2a,
	0x30, 0x6a, 0x70, 0x06, 0x41, 0x38, 0x42, 0x62, 0x5c, 0x6c, 0x25, 0x15, 0x1e, 0x89, 0xc5, 0x19,
	0x12, 0x4c, 0x60, 0x61, 0x28, 0x0f, 0x24, 0x5e, 0x50, 0x9a, 0xe4, 0x9d, 0x5a, 0x29, 0xc1, 0x0c,
	0x11, 0x87, 0xf0, 0x40, 0xa6, 0x80, 0x5c, 0x54, 0x24, 0xc1, 0x02, 0x31, 0x05, 0xcc, 0x81, 0x98,
	0x12, 0x92, 0x99, 0x9b, 0x2a, 0xc1, 0x0a, 0x33, 0x05, 0xc4, 0x73, 0x0a, 0x3c, 0xf1, 0x48, 0x8e,
	0xf1, 0xc2, 0x23, 0x39, 0xc6, 0x07, 0x8f, 0xe4, 0x18, 0x27, 0x3c, 0x96, 0x63, 0xb8, 0xf0, 0x58,
	0x8e, 0xe1, 0xc6, 0x63, 0x39, 0x86, 0x28, 0xf3, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4,
	0xfc, 0x5c, 0xfd, 0x30, 0xa8, 0x8f, 0x5c, 0x60, 0x3e, 0xd2, 0x2f, 0xc8, 0x4f, 0xd6, 0x85, 0x04,
	0x43, 0x85, 0x3e, 0x3c, 0x44, 0x4a, 0x2a, 0x0b, 0x52, 0x8b, 0x93, 0xd8, 0xc0, 0xc1, 0x60, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x12, 0x82, 0x91, 0x9d, 0x2a, 0x01, 0x00, 0x00,
}

func (m *KeysignVoteData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KeysignVoteData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KeysignVoteData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TxTime) > 0 {
		i -= len(m.TxTime)
		copy(dAtA[i:], m.TxTime)
		i = encodeVarintKeysignVoteData(dAtA, i, uint64(len(m.TxTime)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Voter) > 0 {
		i -= len(m.Voter)
		copy(dAtA[i:], m.Voter)
		i = encodeVarintKeysignVoteData(dAtA, i, uint64(len(m.Voter)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.PubKey) > 0 {
		i -= len(m.PubKey)
		copy(dAtA[i:], m.PubKey)
		i = encodeVarintKeysignVoteData(dAtA, i, uint64(len(m.PubKey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TxHash) > 0 {
		i -= len(m.TxHash)
		copy(dAtA[i:], m.TxHash)
		i = encodeVarintKeysignVoteData(dAtA, i, uint64(len(m.TxHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintKeysignVoteData(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintKeysignVoteData(dAtA []byte, offset int, v uint64) int {
	offset -= sovKeysignVoteData(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *KeysignVoteData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovKeysignVoteData(uint64(l))
	}
	l = len(m.TxHash)
	if l > 0 {
		n += 1 + l + sovKeysignVoteData(uint64(l))
	}
	l = len(m.PubKey)
	if l > 0 {
		n += 1 + l + sovKeysignVoteData(uint64(l))
	}
	l = len(m.Voter)
	if l > 0 {
		n += 1 + l + sovKeysignVoteData(uint64(l))
	}
	l = len(m.TxTime)
	if l > 0 {
		n += 1 + l + sovKeysignVoteData(uint64(l))
	}
	return n
}

func sovKeysignVoteData(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozKeysignVoteData(x uint64) (n int) {
	return sovKeysignVoteData(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *KeysignVoteData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowKeysignVoteData
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KeysignVoteData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KeysignVoteData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeysignVoteData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeysignVoteData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeysignVoteData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeysignVoteData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeysignVoteData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeysignVoteData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PubKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeysignVoteData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeysignVoteData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeysignVoteData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PubKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Voter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeysignVoteData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeysignVoteData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeysignVoteData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Voter = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxTime", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowKeysignVoteData
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthKeysignVoteData
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthKeysignVoteData
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxTime = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipKeysignVoteData(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthKeysignVoteData
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipKeysignVoteData(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowKeysignVoteData
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowKeysignVoteData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowKeysignVoteData
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthKeysignVoteData
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupKeysignVoteData
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthKeysignVoteData
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthKeysignVoteData        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowKeysignVoteData          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupKeysignVoteData = fmt.Errorf("proto: unexpected end of group")
)
